### PR TITLE
Requesting code review

### PR DESCRIPTION
**Pull request by matheus-fls**

### CODE REVIEW

**Comment by Ispirett** [comment]
**Hey, Man exceptional work with this project  you are doing a fantastic job :1st_place_medal: . There are just a few changes that Mircoverse requires before this project can be completed.**

### Four images above footer
 - [x] For the section with for I phone pictures the `<a>` tags should have` <div>` tags inside them and  then instead of the image tags use images as the background of the `<div>` tags
### Nav
- [x] User display:flex for buttons inside nav is reommended.

### Footer
 - [x]  Using display flex for positioning links is recommended!


When finished with these changes please submit for another code review you can use this same pull request link.

**Comment by matheus-fls** [comment]
Thank you for your kind support and review Ispirett, I will make the necessary changes and submit the project on Monday. Have a nice weekend!

**Comment by jofer86** [comment]
**Conducting Follow Up Review**

**Comment by jofer86** [comment]
# Great Job, every observation seems to have been taken care of, you can merge to master :+1: :+1: :clap:

**Pull request merged**
